apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-back
  labels:
    app: spring-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-back
  template:
    metadata:
      name: spring-back
      labels:
        app: spring-back
    spec:
      containers:
        - name: spring-back
          image: kurmasasha/spring-amd64:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-config-map
                  key: spring-db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: spring-db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secret
                  key: spring-db-password

---

apiVersion: v1
kind: Service
metadata:
  name: spring-back
spec:
  type: NodePort
  selector:
    app: spring-back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
